In [2]:
import pandas as pd

In [3]:
columns = ["Name", "Age", "Height"]
df = pd.DataFrame(columns=columns)
df

Empty DataFrame
Columns: [Name, Age, Height]
Index: []

In [4]:
df.loc[0] = ["Allen", 22, 175]
df

    Name  Age  Height
0  Allen   22     175

In [5]:
df.loc[1] = ["Ted", 25, 180]
df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180

In [6]:
data = [
    ["Allen", 22, 175],
    ["Ted", 25, 180],
]

df = pd.DataFrame(
    data=data,
    columns=columns,
)

df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180

In [7]:
df["Weight"] = [75, 80]
df

    Name  Age  Height  Weight
0  Allen   22     175      75
1    Ted   25     180      80

In [8]:
df.drop("Weight", axis=1)

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180

In [9]:
df

    Name  Age  Height  Weight
0  Allen   22     175      75
1    Ted   25     180      80

In [14]:
df = df.drop("Weight", axis=1)
df

KeyError: "['Weight'] not found in axis"

In [11]:
df.drop(1)

    Name  Age  Height
0  Allen   22     175

In [12]:
df["Height"]

0    175
1    180
Name: Height, dtype: int64

In [15]:
df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180

In [13]:
df["Height"][1]

np.int64(180)

In [16]:
df["Height"][1] = 188

/var/folders/_k/k5dry95j0q5d35_9pn5d86vm0000gn/T/ipykernel_24765/352499047.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["Height"][1] = 188

In [17]:
df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180

In [19]:
df.loc[1, "Height"] = 188

In [20]:
df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     188

In [21]:
df.loc[1, ["Height", "Age"]]

Height    188
Age        25
Name: 1, dtype: int64

In [22]:
df.loc[[0, 1], ["Height", "Age"]]

   Height  Age
0     175   22
1     188   25

In [23]:
df.loc[0:, "Height":]

   Height
0     175
1     188

In [24]:
df["Height"]

0    175
1    188
Name: Height, dtype: int64

In [25]:
df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     188

In [26]:
df2 = df

In [27]:
df2["Height"] = 100
df2

    Name  Age  Height
0  Allen   22     100
1    Ted   25     100

In [28]:
df

    Name  Age  Height
0  Allen   22     100
1    Ted   25     100

In [29]:
df3 = df.copy()

In [30]:
df3["Age"] = 55
df3

    Name  Age  Height
0  Allen   55     100
1    Ted   55     100

In [31]:
df

    Name  Age  Height
0  Allen   22     100
1    Ted   25     100

In [32]:
# async
# await