In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("holding.parquet")

In [3]:
df

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
13461477,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,2.229475e+04,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
13461478,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148050e+04,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
13461479,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148400e+04,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
13461480,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,1.918738e+04,Endo DAC 6% 30-JUN-2028,29273DAC
13461481,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,1.497188e+04,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [6]:
"""
select * from df limit 3
"""
df.head(3)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644

In [8]:
"""offset"""
df.tail(3)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
13461479,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21484.00,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
13461480,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,19187.38,Endo DAC 6% 30-JUN-2028,29273DAC
13461481,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,14971.88,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [9]:
df[3:8]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
6,2998623,2020/11/30,7,2021/01/08,1.63,2194727.0,1.976352e+08,C S X CORP,12640810
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08,AMERICAN INTERNATIONAL GROUP INC,02687478

In [10]:
df.describe()

       security_rank   percent_tna    nbr_shares    market_val
count   1.346148e+07  1.346148e+07  1.346148e+07  1.346148e+07
mean    5.865976e+02  4.404682e-01  2.438436e+07  1.137428e+07
std     8.539445e+02  2.125681e+00  6.523191e+09  1.651424e+08
min     1.000000e+00 -2.489000e+02 -1.027540e+12 -6.520285e+09
25%     8.200000e+01  2.000000e-02  5.744000e+03  1.153754e+05
50%     2.750000e+02  8.000000e-02  5.249300e+04  6.464532e+05
75%     7.270000e+02  3.100000e-01  4.488590e+05  3.176073e+06
max     8.716000e+03  3.028200e+02  6.667220e+12  7.118158e+10

In [11]:
df.dtypes

portno               str
report_dt            str
security_rank      int64
eff_dt               str
percent_tna      float64
nbr_shares       float64
market_val       float64
security_name        str
cusip                str
dtype: object

In [12]:
df

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
13461477,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,2.229475e+04,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
13461478,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148050e+04,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
13461479,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148400e+04,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
13461480,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,1.918738e+04,Endo DAC 6% 30-JUN-2028,29273DAC
13461481,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,1.497188e+04,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [13]:
"""
select count(distinct(portno)) from df
"""
df["portno"].unique()

<ArrowStringArray>
['2998623', '2998638', '2998809', '2998821', '3000255', '300035d', '3001404',
 '3002313', '3002316', '300251d',
 ...
 '3156837', '3156924', '3157206', '3157233', '315723c', '3157245', '315724b',
 '315724e', '3157332', '3157350']
Length: 9453, dtype: str

In [14]:
df["cusip"].unique()

<ArrowStringArray>
['37045V10', '19244610', '61744644', '71817210', '22052L10', '38141G10',
 '12640810', '02687478', '69347510', '12504L10',
 ...
 '421722K8', '353187EJ', '235241WQ', '130483ES', '59211SAA', '05491UBA',
 '61767EAC', '98163EAE', '03066RAC', '44891RAD']
Length: 257261, dtype: str

In [15]:
df["security_name"].unique()

<ArrowStringArray>
[                                                                      'GENERAL MOTORS CO',
                                                          'COGNIZANT TECHNOLOGY SOLS CORP',
                                                         'MORGAN STANLEY DEAN WITTER & CO',
                                                         'PHILIP MORRIS INTERNATIONAL INC',
                                                                             'CORTEVA INC',
                                                                 'GOLDMAN SACHS GROUP INC',
                                                                              'C S X CORP',
                                                        'AMERICAN INTERNATIONAL GROUP INC',
                                                        'P N C FINANCIAL SERVICES GRP INC',
                                                                       'C B R E GROUP INC',
 ...
                                                        'State of Colorado 5% 15-DEC-2034',
                                         'BBCMS TRUST 18C2 ASB PAC FIX 4.236% 15-DEC-2051',
 'MORGAN STANLEY BANK OF AMERICA MERRILL LYNCH TRUST 17C34 ASB PAC FIX 3.354% 15-NOV-2052',
                                   'COMM MORTGAGE TRUST 13CC13 C VAR 4.88008% 12-NOV-2046',
         'JPMBB COMMERCIAL MORTGAGE SECURITIES TRUST 15C27 A4 SEQ FIX 3.1794% 18-FEB-2048',
                       'WORLD OMNI AUTO RECEIVABLE TRUST 18C A4 SEQ FIX 3.27% 16-SEP-2024',
                                 'BMW VEHICLE OWNER TRUST 20A A4 SEQ FIX .62% 26-APR-2027',
                'AMERICREDIT AUTOMOBILE RECEIVABLES TRUST 212 A3 SEQ FIX .34% 18-DEC-2026',
                              'HYUNDAI AUTO RECEIVABLES TRUST 20C A4 FIX .49% 16-NOV-2026',
                                'COMM MORTGAGE TRUST 15CC26 D SEQ VAR 3.4782% 13-OCT-2048']
Length: 342685, dtype: str

In [21]:
"""
select
    portno,
    eff_dt,
    sum(percent_tna)
from df
group by portno, eff_dt
"""
df.groupby(["portno", "eff_dt"], as_index=False)["percent_tna"].sum()

        portno      eff_dt  percent_tna
0      2998623  2021/01/08        99.79
1      2998623  2021/02/05        99.20
2      2998623  2021/05/10        99.96
3      2998623  2021/06/07        99.93
4      2998623  2021/08/09        99.78
...        ...         ...          ...
59334  3157308  2021/12/07       100.23
59335  315732c  2021/12/07       100.12
59336  3157332  2021/12/21        99.94
59337  315733b  2021/12/07        99.73
59338  3157350  2021/12/21        99.55

[59339 rows x 3 columns]

In [23]:
"""
select
    portno,
    eff_dt,
    sum(percent_tna)
from df
group by portno, eff_dt
order by portno, eff_dt desc
"""
df_sorted = (
    df
    .groupby(["portno", "eff_dt"], as_index=False)["percent_tna"]
    .sum()
    .sort_values(["portno", "eff_dt"], ascending=False)
)

df_sorted

        portno      eff_dt  percent_tna
59338  3157350  2021/12/21        99.55
59337  315733b  2021/12/07        99.73
59336  3157332  2021/12/21        99.94
59335  315732c  2021/12/07       100.12
59334  3157308  2021/12/07       100.23
...        ...         ...          ...
4      2998623  2021/08/09        99.78
3      2998623  2021/06/07        99.93
2      2998623  2021/05/10        99.96
1      2998623  2021/02/05        99.20
0      2998623  2021/01/08        99.79

[59339 rows x 3 columns]