In [1]:
import pandas as pd

df = pd.read_csv("employees.csv")
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com
5        E006          NaN          NaN      NaN                      NaN

In [2]:
type(None)

NoneType

In [4]:
None

In [3]:
df["salary"][4]

np.float64(nan)

In [5]:
df["salary"].mean()

np.float64(72500.0)

In [6]:
df["salary"].fillna(0)

0    95000.0
1    72000.0
2    68000.0
3    55000.0
4        0.0
5        0.0
Name: salary, dtype: float64

In [7]:
df["salary"].fillna(0).mean()

np.float64(48333.333333333336)

In [8]:
df["salary"] = df["salary"].fillna(0)
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      0.0  eve.johnson@company.com
5        E006          NaN          NaN      0.0                      NaN

In [9]:
df.dropna()

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
4        E005  Eve Johnson        Sales      0.0  eve.johnson@company.com

In [10]:
df.dropna(thresh=2)

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      0.0  eve.johnson@company.com
5        E006          NaN          NaN      0.0                      NaN

In [11]:
df.dropna(thresh=3)

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
4        E005  Eve Johnson        Sales      0.0  eve.johnson@company.com

In [12]:
df["name"].isnull()

0    False
1    False
2    False
3     True
4    False
5     True
Name: name, dtype: bool

In [13]:
df[df["name"].isnull()]

  employee_id name department   salary email
3        E004  NaN        NaN  55000.0   NaN
5        E006  NaN        NaN      0.0   NaN

In [15]:
df[df["name"].isna()]

  employee_id name department   salary email
3        E004  NaN        NaN  55000.0   NaN
5        E006  NaN        NaN      0.0   NaN

In [14]:
df[df["name"].notna()]

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
4        E005  Eve Johnson        Sales      0.0  eve.johnson@company.com

In [16]:
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      0.0  eve.johnson@company.com
5        E006          NaN          NaN      0.0                      NaN

In [17]:
df["department"].ffill()

0    Engineering
1      Marketing
2      Marketing
3      Marketing
4          Sales
5          Sales
Name: department, dtype: str

In [18]:
df["department"] = df["department"].ffill()
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White    Marketing  68000.0  carol.white@company.com
3        E004          NaN    Marketing  55000.0                      NaN
4        E005  Eve Johnson        Sales      0.0  eve.johnson@company.com
5        E006          NaN        Sales      0.0                      NaN

In [19]:
import numpy as np

In [20]:
np.where(
    df["email"].isna(),
    "unknown",
    df["email"],
)

array(['alice.chen@company.com', 'unknown', 'carol.white@company.com',
       'unknown', 'eve.johnson@company.com', 'unknown'], dtype=object)

In [21]:
df["email"] = np.where(
    df["email"].isna(),
    "unknown",
    df["email"],
)

df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                  unknown
2        E003  Carol White    Marketing  68000.0  carol.white@company.com
3        E004          NaN    Marketing  55000.0                  unknown
4        E005  Eve Johnson        Sales      0.0  eve.johnson@company.com
5        E006          NaN        Sales      0.0                  unknown

In [23]:
for i in range(5):
    print(i, "odd" if i%2 == 1 else "even")

0 even
1 odd
2 even
3 odd
4 even