In [1]:
import pandas as pd

In [2]:
path_staff = "staff.csv"
path_staff_detail = "staff_detail.csv"
path_staff_detail_different_col = "staff_detail_different_col.csv"
path_staff_samecol = "staff_samecol.csv"

df_staff = pd.read_csv(path_staff)
df_staff_detail = pd.read_csv(path_staff_detail)
df_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)
df_staff_samecol = pd.read_csv(path_staff_samecol)

In [4]:
df_staff_detail.merge(
    df_staff,
    how="left",
    left_on="ID",
    right_on="ID",
)

    ID Level  UpdateDate   Name  DeptId  Age Gender  Salary
0    1     A  2019-08-09   Mike       2   45      M   60000
1    1     S  2020-12-08   Mike       2   45      M   60000
2    2     A  2021-05-30   Judy       2   30      F   48000
3    3     A  2018-03-26  Allen       1   22      M   50000
4    3     S  2020-12-08  Allen       1   22      M   50000
5    4     A  2022-05-02    Tom       2   47      M   47000
6    5     A  2019-11-05   Jack       3   36      M   52000
7    5     S  2022-04-25   Jack       3   36      M   52000
8    6     A  2022-03-03   Abby       2   24      F   45000
9    7     A  2017-03-29  Trump       1   80      M   80000
10   7     S  2018-05-02  Trump       1   80      M   80000
11   7     M  2021-09-01  Trump       1   80      M   80000
12   8     A  2018-11-26  Marry       3   29      F   87000
13   8     S  2020-03-15  Marry       3   29      F   87000
14   8     M  2022-05-03  Marry       3   29      F   87000

In [7]:
df_staff_detail_different_col.merge(
    df_staff_samecol,
    how="left",
    left_on="EmpNum",
    right_on="ID",
    suffixes=["_left", "_right"]
)[
    [
        "EmpNum",
        "Level",
        "Name",
        "Salary",
    ]
]

    EmpNum Level   Name  Salary
0        1     A   Mike   60000
1        1     S   Mike   60000
2        2     A   Judy   48000
3        3     A  Allen   50000
4        3     S  Allen   50000
5        4     A    Tom   47000
6        5     A   Jack   52000
7        5     S   Jack   52000
8        6     A   Abby   45000
9        7     A  Trump   80000
10       7     S  Trump   80000
11       7     M  Trump   80000
12       8     A  Marry   87000
13       8     S  Marry   87000
14       8     M  Marry   87000